### ISSUE TITLE
Compile C code to R1CS

### ISSUE THREAD

**Issue by OmarAlmighty** [circify/circ#173]
Are there any instructions or examples that explain how to compile a C program into R1CS? I could find the `add.c` file in the [examples](https://github.com/circify/circ/tree/master/examples)/[C](https://github.com/circify/circ/tree/master/examples/C)/[r1cs](https://github.com/circify/circ/tree/master/examples/C/r1cs) directory, but I don't know how to compile it.

**Comment by OmarAlmighty** [comment]
Okay! I've figured out how to compile the `add.c`. I had to build the project, turning on a couple of features, using the following command: `cargo build --features r1cs,smt,zok,c,bellman --example circ`. Then, I navigated to  **circ/target/debug/examples** and ran the `circ` binary using the command `./circ --language c <path_to_your_c_code> r1cs`

### I still don't know ...
where the R1CS output file is written to or how to parse/deal with it in case I am going to use it in another code.

**Comment by alex-ozdemir** [comment]
Thanks for reaching out, and for your interest in CirC.
Short answer: we've never fleshed out the C->R1CS pipeline in CirC's Rust
implementation. I would recommend using the ZoKrates/Z# front-end instead.

Long answer:

When we did the first implementation of CirC (in Haskell)[1], C was one of our
test languages, and [1] is a state-of-the-art compiler from C to R1cs. See
these tests[2], but note: we don't maintain it anymore.

We haven't focused on the C->R1CS pipeline in the Rust version of CirC[3],
because C is generally a bad language to compile to R1CS. But, there is a C
front-end (for other reasons) and if you know how to hack compilers, it
wouldn't take too much work to hook it up to the R1CS back-end. I'm happy to
give you some pointers if you want to do that.

Another option for C->R1CS is Pequin (which, IIRC, is unmaintained).

**Comment by alex-ozdemir** [comment]
(discussed offline; feel free to re-open)
