### ISSUE TITLE
Cannot perform op `==` on array and array

### ISSUE THREAD

**Issue by sshravan** [circify/circ#2]
```
def main(u32[8] a):

	assert(a == [0; 8])
	return
```

Circ returns the following error message:
```
Options { zokrates_path: "test.zok", inputs: None, parties: None }
Error: Cannot perform op '==' on array and array
In: test.zok
  	assert(a == [0; 8])
```

Would it be possible to support `==` on arrays? This feature is available in ZoKrates 0.6.3.

**Comment by kwantam** [comment]
With zok0.7 syntax, array equality is easy to implement using generic (over array length) functions---though you'll still need a separate function for each type contained in the array.

Struct equality is slightly more annoying, since in princple you'd have to write an equality checking function for each field (which feels like a lot of boilerplate).

I suppose all of the above are possible to do automatically. Shouldn't be hard to add. Keeping this open until we figure out how to proceed (presumably on the zsharp branch)

**Comment by kwantam** [comment]
#30 fixed this. closing.
