### ISSUE TITLE
cfold: divide by zero semantics

### ISSUE THREAD

**Issue by kwantam** [circify/circ#69]
https://github.com/circify/circ/blob/c784bf70548483a2d45b3c60819bf2e7ca9df834/src/ir/opt/cfold.rs#L104-L107

Unless I'm missing something, the divide-by-zero semantics here are to return uint-max for the given bit width. That seems wrong. Shouldn't this just panic?

**Comment by kwantam** [comment]
I see now that this is implementing SMT bitvector division semantics. Is that really what we want here? Hmm.

**Comment by alex-ozdemir** [comment]
This is intentional: our IR semantics are generally just SMT.
More broadly, right now our IR semantics generally are total (evaluation is possible for all inputs).
This generally allows a front-end to implement whatever total (or partial) semantics it wants. For example, a C front-end can set a global "error" bit if it wants those semantics.
